# Generated by Django 5.2 on 2025-06-21 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('sector', models.CharField(max_length=100)),
                ('tamano', models.CharField(choices=[('micro', 'Microempresa'), ('pequena', 'Pequeña Empresa'), ('mediana', 'Mediana Empresa')], max_length=50)),
                ('descripcion_negocio', models.TextField()),
                ('recursos_disponibles', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estrategia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_estrategia', models.CharField(choices=[('marketing', 'Marketing'), ('ventas', 'Ventas'), ('operaciones', 'Operaciones'), ('expansion', 'Expansión'), ('digital', 'Digitalización'), ('financiera', 'Financiera')], max_length=100)),
                ('descripcion_estrategia', models.TextField()),
                ('impacto_estimado', models.TextField(blank=True, null=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estrategias.empresa')),
            ],
        ),
    ]
